version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-nano}
      - APP_NAME=${APP_NAME:-Web BigDataCup API}
      - DEBUG=${DEBUG:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-["http://localhost:5173"]}
    volumes:
      - ./backend:/code

    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
      - VITE_PLAYER_NODE_RADIUS=${VITE_PLAYER_NODE_RADIUS:-12}
      - VITE_PLAYER_NODE_STROKE_COLOR=${VITE_PLAYER_NODE_STROKE_COLOR:-#000000}
      - VITE_PLAYER_NODE_FILL_HOME=${VITE_PLAYER_NODE_FILL_HOME:-#2563eb}
      - VITE_PLAYER_NODE_FILL_AWAY=${VITE_PLAYER_NODE_FILL_AWAY:-#dc2626}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

